version: "3.7"
services:
  rtl:
    container_name: rtl 
    image: shahanafarooqui/rtl:0.12.0
    restart: unless-stopped
    expose:
      - 3009
    environment:
      PORT: 3009
      HOST: 0.0.0.0
      RTL_CONFIG_PATH: /data
      MACAROON_PATH: /etc/rest_certs
    volumes:
      - "rest_certs:/etc/rest_certs"
      - "rtl_data:/data"
    networks: 
      - cyphernodeappsnet
    labels:
      - traefik.docker.network=cyphernodeappsnet
      - traefik.frontend.redirect.entryPoint=https
      - traefik.frontend.rule=PathPrefix:/rtl
      - traefik.frontend.passHostHeader=true
      - traefik.enable=true
      - traefik.port=3009
      labels:
        - traefik.docker.network=cyphernodeappsnet
        - traefik.frontend.redirect.entryPoint=https
        - traefik.frontend.rule=PathPrefix:/rtl
        - traefik.frontend.passHostHeader=true
        - traefik.enable=true
        - traefik.port=3009
      replicas: 1
      placement:
        constraints:
          - node.labels.io.cyphernode == true
      restart_policy:
        delay: 1s
      update_config:
        parallelism: 1

  clrest:
    container_name: clrest 
    image: saubyk/c-lightning-rest:0.10.2
    restart: unless-stopped
    environment:
      PROTOCOL: "http"
      NODE: lightning:9735
    volumes:
      - "bitcoin_data:/etc/bitcoin"
      - "lightning_data:/root/.lightning"
      - "rest_certs:/usr/src/app/certs"
    expose:
      - 3001
    networks:
        - cyphernodenet
        - cyphernodeappsnet

volumes:
  rtl_data:
    driver: local
    driver_opts:
      type: none
      device: "$RTL_DATAPATH"
      o: bind
  bitcoin_data:
    driver: local
    driver_opts:
      type: none
      device: "$BITCOIN_DATAPATH"
      o: bind
  lightning_data:
    driver: local
    driver_opts:
      type: none
      device: "$LIGHTNING_DATAPATH"
      o: bind
  rest_certs:

networks:
  cyphernodenet:
    external: true
  cyphernodeappsnet:
    external: true
